### ISSUE TITLE
获取验证码时报错Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wolfing88** [King-stark/NvJDCloud#1]
![image](https://user-images.githubusercontent.com/22385050/148673144-6653aa4f-fa2a-4c4e-9166-ca9a7fba3eda.png)

**Comment by King-stark** [comment]
![image](https://user-images.githubusercontent.com/63186186/148693301-6a69f317-d2f2-453c-a188-89bc7ba4502b.png)

作者群里的回复
